// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hsarqhniuyqikzwxdjet.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhzYXJxaG5pdXlxaWt6d3hkamV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3NTg3NzgsImV4cCI6MjA3NDMzNDc3OH0.SjmKqQy6N5Yr3O5Yc0fC8Wk0CLfju1Myq3SZexjAoqY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});